### ISSUE TITLE
Some existing resources do not show up in generator data set

### ISSUE THREAD

**Issue by fikrikscg** [PowerGenome/PowerGenome#96]
I tried to add the following existing resources, but they do not show up. I could not figure out the reason. What I realized is that their sizes are too small. I am not sure if there is a capacity threshold below which resources do not show up in generator data set.

Offshore Wind Turbine
Coal Integrated Gasification Combined Cycle
Flywheels
Natural Gas with Compressed Air Storage

**Comment by gschivley** [comment]
No, there shouldn't be a capacity threshold. Offshore wind turbines are an issue I'll have to fix soon. If a resource isn't included in the EPA NEEDS database (which links plants to IPM regions), they are assigned via a geospatial join. But offshore areas aren't included in the IPM shapefile.

I'm less sure why the other resources aren't included. Do you mind sharing your `num_clusters` and `retirement_ages` parameters? 

You'll also want to make sure that these technologies are added to the `eia_atb_tech_map` parameter, with whatever you think the best match is for fixed & variable O&M. PG uses a NEMS report for existing plant O&M, but technologies that aren't included in it use O&M from NREL ATB instead.

**Comment by gschivley** [comment]
The only correction I'd make is in `eia_atb_tech_map`. You associate flywheels with "Battery_2Hr Battery Storage", but I separated the capacity/energy costs from NREL so that models can decide how many hours of storage they want. The `technology` is Battery and the `tech_detail` is "\*" (Battery_\*).  

Are you including all IPM regions where the technologies are located? I have a test file with all IPM regions in a single model region and was able to see clusters.

![image](https://user-images.githubusercontent.com/10373332/111566519-adb15180-8773-11eb-89a4-8b0ab031b48b.png)

**Comment by fikrikscg** [comment]
Thank you for the correction regarding flywheels.

As for the existing resources which I claimed not show up in the generator data set, I am so sorry for the stupid mistake. I never checked where these resources are located. All of these are located out of WECC region, but I am running PowerGenome to get input data for WECC. So, there is nothing wrong with it. I should have checked this before I open this issue. I apologize again. I think this issue can be closed.
